<a href="https://colab.research.google.com/github/danacioDS/AI-ML-SimpliLearn/blob/master/02_Random_Forest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Loading the library with the iris data set 
from sklearn.datasets import load_iris

In [ ]:
# Loading sci kit random forest classifier library

from sklearn.ensemble import RandomForestClassifier

In [ ]:
# Loading libraries 
import pandas as pd
import numpy as np

In [ ]:
np.random.seed(0)

In [ ]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns = iris.feature_names)

In [ ]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [ ]:
df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)

df.head()

sepal length (cm)  sepal width (cm)  ...   good   culo
0                5.1               3.5  ...   True  False
1                4.9               3.0  ...  False  False
2                4.7               3.2  ...   True   True
3                4.6               3.1  ...   True   True
4                5.0               3.6  ...   True   True

[5 rows x 8 columns]

In [ ]:
# delete columns in pnadas 
del df['column_name']

In [ ]:
df['is_train'] = np.random.uniform(0, 1, len(df)) <= .75

df.head()

sepal length (cm)  sepal width (cm)  ...  species  is_train
0                5.1               3.5  ...   setosa     False
1                4.9               3.0  ...   setosa      True
2                4.7               3.2  ...   setosa      True
3                4.6               3.1  ...   setosa      True
4                5.0               3.6  ...   setosa     False

[5 rows x 6 columns]

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
train, test = df[df['is_train']==True], df[df['is_train']==False]

In [ ]:
print('Number of obvservations in the traning data:', len(train))
print('Number of obsevations in the test data:', len(test))

Number of obvservations in the traning data: 112
Number of obsevations in the test data: 38


In [ ]:
features = df.columns[:4]

In [ ]:
features

Index(['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)',
       'petal width (cm)'],
      dtype='object')

In [ ]:
y = pd.factorize(train['species'])[0]
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2])

In [ ]:
# Creating a random Forest Classifier

clf = RandomForestClassifier(n_jobs=2, random_state = 0)

clf.fit(train[features], y)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100, n_jobs=2,
                       oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [ ]:
# Apply the trained Classifier to the test

clf.predict(test[features])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 2, 2, 2, 1, 2, 2])

In [ ]:
# Viewing the predicted probabilities to the first 10 observations

clf.predict_proba(test[features])[10:20]


array([[1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [1.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  ],
       [0.  , 0.99, 0.01],
       [0.  , 0.98, 0.02],
       [0.  , 1.  , 0.  ],
       [0.  , 0.8 , 0.2 ],
       [0.  , 0.99, 0.01]])

In [ ]:
# mapping names for the plants for each predicted pant class

preds = iris.target_names[clf.predict(test[features])]


In [ ]:
# View the predicted species for the firtst five observations 

preds[0:25]

array(['setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'setosa', 'setosa', 'setosa', 'setosa',
       'setosa', 'setosa', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor',
       'versicolor', 'versicolor', 'versicolor', 'versicolor'],
      dtype='<U10')

In [ ]:
# Viewin the Actual Species for the fisrt five observations 

test['species'].head(15)

0         setosa
4         setosa
5         setosa
10        setosa
12        setosa
14        setosa
18        setosa
23        setosa
25        setosa
28        setosa
30        setosa
35        setosa
39        setosa
49        setosa
51    versicolor
Name: species, dtype: category
Categories (3, object): [setosa, versicolor, virginica]

In [ ]:
# Creating confusion matrix
pd.crosstab(test['species'], preds, rownames=['Actual Species'],
            colnames=['Predicted Species'])


Predicted Species  setosa  versicolor  virginica
Actual Species                                  
setosa                 14           0          0
versicolor              0          13          0
virginica               0           2          9